# Generated by Django 4.2.4 on 2023-08-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shelf', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=256)),
                ('required', models.DecimalField(decimal_places=0, default=0, max_digits=256)),
                ('consum', models.FloatField(default=0)),
                ('until', models.FloatField(default=0)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
