# Generated by Django 4.2.4 on 2023-08-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Food',
        ),
    ]
